// <auto-generated />
using System;
using Lesson01_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309061030_v1243231")]
    partial class v1243231
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lesson01_API.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Electronics",
                            Description = "Electronic devices and gadgets"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Computers",
                            Description = "Desktops, laptops and accessories",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Home",
                            Description = "Home and kitchen appliances"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Books",
                            Description = "Printed and digital books"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Clothing",
                            Description = "Men and women apparel"
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "100 Main St",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "555-0100"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "101 Main St",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "102 Main St",
                            Email = "sam.green@example.com",
                            FirstName = "Sam",
                            LastName = "Green",
                            PhoneNumber = "555-0102"
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Promode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            BillingAddress = "100 Main St",
                            CustomerID = 1,
                            DeliveredDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Promode = "Standard",
                            ShippedDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "100 Main St",
                            Status = "Pending",
                            TotalAmount = 1214.99m
                        },
                        new
                        {
                            OrderId = 2,
                            BillingAddress = "101 Main St",
                            CustomerID = 2,
                            DeliveredDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Promode = "Express",
                            ShippedDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "101 Main St",
                            Status = "Shipped",
                            TotalAmount = 899.99m
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            Discount = 0,
                            OrderID = 1,
                            ProductID = 1,
                            Quantity = 1,
                            UnitPrice = 1200
                        },
                        new
                        {
                            OrderDetailID = 2,
                            Discount = 0,
                            OrderID = 1,
                            ProductID = 4,
                            Quantity = 1,
                            UnitPrice = 14
                        },
                        new
                        {
                            OrderDetailID = 3,
                            Discount = 0,
                            OrderID = 2,
                            ProductID = 2,
                            Quantity = 1,
                            UnitPrice = 899
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("StandardCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryId = 2,
                            Description = "Lightweight laptop",
                            IsActive = true,
                            Name = "Laptop Model A",
                            Price = 1200.00m,
                            Quantity = 10,
                            StandardCost = 800.00m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryId = 1,
                            Description = "Latest smartphone",
                            IsActive = true,
                            Name = "Smartphone X",
                            Price = 899.99m,
                            Quantity = 25,
                            StandardCost = 600.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryId = 3,
                            Description = "High-speed blender",
                            IsActive = true,
                            Name = "Blender 3000",
                            Price = 99.50m,
                            Quantity = 40,
                            StandardCost = 55.00m,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryId = 4,
                            Description = "Fiction book",
                            IsActive = true,
                            Name = "Novel - The Journey",
                            Price = 14.99m,
                            Quantity = 100,
                            StandardCost = 6.00m,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryId = 5,
                            Description = "Cotton T-Shirt",
                            IsActive = true,
                            Name = "T-Shirt Classic",
                            Price = 19.99m,
                            Quantity = 200,
                            StandardCost = 5.00m,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "123 Acme Way",
                            ContactName = "Alice Smith",
                            Email = "alice@acme.example",
                            IsActive = true,
                            Phone = "123-456-7890",
                            SupplierName = "Acme Corp"
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "456 Tech Drive",
                            ContactName = "Bob Jones",
                            Email = "bob@globaltech.example",
                            IsActive = true,
                            Phone = "234-567-8901",
                            SupplierName = "Global Tech"
                        },
                        new
                        {
                            SupplierID = 3,
                            Address = "789 Home St",
                            ContactName = "Carol White",
                            Email = "carol@homegoods.example",
                            IsActive = true,
                            Phone = "345-678-9012",
                            SupplierName = "Home Goods Co"
                        });
                });

            modelBuilder.Entity("Lesson01_API.Models.Category", b =>
                {
                    b.HasOne("Lesson01_API.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Lesson01_API.Models.Order", b =>
                {
                    b.HasOne("Lesson01_API.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lesson01_API.Models.OrderDetail", b =>
                {
                    b.HasOne("Lesson01_API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson01_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lesson01_API.Models.Product", b =>
                {
                    b.HasOne("Lesson01_API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lesson01_API.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lesson01_API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lesson01_API.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lesson01_API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Lesson01_API.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
